#!/bin/sh

readlink() {
	path=$1

	if [ -L "$path" ]
	then
		ls -l "$path" | sed 's/^.*-> //'
	else
		return 1
	fi
}

SCRIPT="$0"
COUNT=0
while [ -L "${SCRIPT}" ]
do
	SCRIPT=$(readlink ${SCRIPT})
	COUNT=$(expr ${COUNT} + 1)
	if [ ${COUNT} -gt 100 ]
	then
		echo "Too many symbolic links"
		exit 1
	fi
done
GAMEDIR=$(dirname "${SCRIPT}")

cd $GAMEDIR

export LD_LIBRARY_PATH="./lib"

./openmw-launcher "$@"
if [ ! $? -eq 0 ]; then
    zenity --question --title="OpenMW Missing Dependency" --text "Qt4 is missing from this system. Would you like to continue loading the game without the launcher?"
    if [ $? = 0 ] ; then
        configdirectory="$HOME/.config/openmw" #Fix to use XDG?
        if [ ! -d "$configdirectory" ]; then
            mkdir $configdirectory
            SCRIPT_PATH=$(dirname $(realpath -s $0))
            cp "$SCRIPT_PATH/openmw-cfg-template.cfg" "$configdirectory/openmw.cfg"
            echo -e "data=\""$SCRIPT_PATH/Data Files\""" >> "$configdirectory/openmw.cfg"
        fi
        ./openmw-bin "$@" --resources=resources
    fi
fi
