name: Build Engine

on:
  push:
    branches: [ test ]

jobs:
  findengine:
    runs-on: ubuntu-latest
    outputs:
      engine: ${{ steps.findname.outputs.engine }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Find Engine Name
      id: findname
      run: echo "::set-output name=engine::test123"
  build:
    runs-on: ubuntu-latest
    needs: findengine
    container:
      image: luxtorpeda/steam-runtime-amd64-beta:lux-190812-1
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: mkdir dist && touch dist/test1 && touch dist/test2
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: ./dist
  finddeploy:
    needs: [build]
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.findname.outputs.matrix }}
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: dist
      - name: Find Engine Name
        id: findname
        uses: luxtorpeda-dev/action-build-generate-file-matrix@master
        with:
            name: dist
  deploy:
    needs: finddeploy
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.finddeploy.outputs.matrix)}}
    steps:
    - name: test
      run: echo "${{ matrix.name }} ${{ matrix.fileName }}"
