name: Build Engine

on:
  push:
    branches: [ test ]

jobs:
  findengine:
    runs-on: ubuntu-latest
    outputs:
      engine: ${{ steps.findname.outputs.engine }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Find Engine Name
      id: findname
      run: echo "::set-output name=engine::test123"
    - name: Create Package on Bintray
      uses: benjefferies/create-bintray-package@c74a218
      with:
        bintray-user: ${{ secrets.BINTRAY_USER }}
        bintray-token: ${{ secrets.BINTRAY_API_KEY }}
        owner: ${{ secrets.BINTRAY_OWNER }}
        repo: ${{ secrets.BINTRAY_REPO }}
        package-name: ${{ steps.findname.outputs.engine }}
        package-description: Package for ${{ steps.findname.outputs.engine }}
        package-url: NONE
        package-license: GPL-2.0
  build:
    runs-on: ubuntu-latest
    needs: findengine
    container:
      image: luxtorpeda/steam-runtime-amd64-beta:lux-190812-1
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: mkdir dist && touch dist/test1 && touch dist/test2
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: ./dist
  finddeploy:
    needs: [build]
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: dist
      - name: Generate Matrix
        id: matrix
        uses: luxtorpeda-dev/action-build-generate-file-matrix@master
        with:
          name: dist
  deploy:
    needs: [finddeploy, findengine]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.finddeploy.outputs.matrix)}}
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v1
      with:
        name: dist
    - name: Upload Package to Bintray
      uses: bpicode/github-action-upload-bintray@master
      with:
        file: ${{ matrix.fileName }}
        api_user: ${{ secrets.BINTRAY_USER }}
        api_key: ${{ secrets.BINTRAY_API_KEY }}
        repository_user: ${{ secrets.BINTRAY_OWNER }}
        repository: ${{ secrets.BINTRAY_REPO }}
        package: ${{ steps.findname.outputs.engine }}
        version: ${{ github.sha }}
        publish: 1
