name: Check Download Status

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * MON'

jobs:
  check_status:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.check_download_status.outputs.matrix }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Check Download Status
      id: check_download_status
      uses: luxtorpeda-dev/actions/check-download-status@main
  create_tickets:
    runs-on: ubuntu-latest
    if: ${{ needs.check_status.outputs.matrix && needs.check_status.outputs.matrix != '{}' && needs.check_status.outputs.matrix != '' }}
    needs: check_status
    strategy:
      matrix: ${{fromJson(needs.check_status.outputs.matrix)}}
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Create Issue for network
      if: ${{ matrix.type == 'network_error' }}
      uses: JasonEtco/create-an-issue@v2
      with:
        filename: .github/workflow_issue_templates/download_network_error.yml
        update_existing: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GAME_NAME: ${{ matrix.game_name }}
        DOWNLOAD_NAME: ${{ matrix.download_name }}
        DOWNLOAD_STATUS: ${{ matrix.download_status }}
        DOWNLOAD_STATUS_TEXT: ${{ matrix.download_status_text }}
        GAME_APP_ID: ${{ matrix.game_app_id }}
        FULL_URL: ${{ matrix.full_url }}
    - name: Update download release references
      if: ${{ matrix.type == 'new_release' }}
      uses: luxtorpeda-dev/actions/update-engine-version@main
      with:
        engineName: ${{ matrix.engineName }}
        newTag: ${{ matrix.newTag }}
        oldTag: ${{ matrix.oldTag }}
        updateDownloads: true

    - uses: actions/create-github-app-token@v3
      if: ${{ matrix.type == 'new_release' }}
      id: generate-token
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
        owner: luxtorpeda-dev

    - name: Create Pull Request
      if: ${{ matrix.type == 'new_release' }}
      uses: peter-evans/create-pull-request@v8
      with:
        commit-message: ${{ matrix.engineName }} - Update to ${{ matrix.newTag }}
        branch: update-${{ matrix.engineName }}-${{ matrix.newTag }}
        title: Update ${{ matrix.engineName }} to ${{ matrix.newTag }}
        assignees: d10sfan
        token: ${{ steps.generate-token.outputs.token }}
