name: Check For Engine Releases Hash

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * MON'

jobs:
  check_status:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.check_release.outputs.matrix }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Check Download Status
      id: check_release
      uses: luxtorpeda-dev/action-check-new-engine-release@main
      with:
        github_token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        commit_mode: hash
  create_prs:
    runs-on: ubuntu-latest
    if: ${{ needs.check_status.outputs.matrix && needs.check_status.outputs.matrix != '{}' && needs.check_status.outputs.matrix != '' }}
    needs: check_status
    strategy:
      matrix: ${{fromJson(needs.check_status.outputs.matrix)}}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Update Engine
      uses: luxtorpeda-dev/action-update-engine-version@main
      with:
        engineName: ${{ matrix.engineName }}
        newTag: ${{ matrix.newTag }}
        oldTag: ${{ matrix.oldTag }}
        newHash: ${{ matrix.newHash }}
        oldHash: ${{ matrix.oldHash }}
    - uses: actions/create-github-app-token@v2
      id: generate-token
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
        owner: luxtorpeda-dev
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: ${{ matrix.engineName }} - Update
        branch: update-${{ matrix.engineName }}
        title: Update ${{ matrix.engineName }}
        assignees: d10sfan
        token: ${{ steps.generate-token.outputs.token }}
